django-example/mysite/myapp/urls.py
from django.contrib import admin
from django.urls import path
from myapp import views

# "myapp" we pass this name in index.html file
# in the url section so jango comes here for detail named view
# it means we have name space here "myapp"
app_name = "myapp"

urlpatterns = [
    path("", views.index, name="index"),
    # here we use the id that we passed it in views
    # then because it is a intiger value
    # we covert it like this
    path("book/<int:book_id>/", views.detail, name="detail"),
    path("add/", views.add_book, name="add_book"),
    path("edit/<int:id>/", views.edit, name="edit"),
    path("delete/<int:id>/", views.delete, name="delete"),
]

django-example/mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from myapp import views
from .import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    # we include urls.py file in myapp folder like this
    # thre was not a folder urls.py in myapp directory
    # we create it copied all paths to that folder
    path("", include("myapp.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django-example/mysite/myapp/models.py
from django.db import models

# Create your models here.


class Book(models.Model):

    # this function let us when we type Book.objects.all().
    # to get the objects name instead geting Book object().

    def __str__(self):
        return self.name

    # name is a field for book, we say that to django it is char with max_length = 100 char for each book name
    name = models.CharField(max_length=100)
    # desc = description
    desc = models.CharField(max_length=300)
    price = models.IntegerField()
    book_image = models.ImageField(default='default.jpg', upload_to='book_images/')

django-example/mysite/myapp/forms.py
from django import forms
from .models import Book

# this name means(we have a model with name of Book) we want to create a form for this model
# and it inherits from = forms.ModelForm


class BookForm(forms.ModelForm):
    class Meta:
        # we can not go direcly to declare model and feils we should first declare meta class then
        # model and feilds should be inside the meta class
        # meta is a class that holds class information
        # class Meta:
        model = Book
        fields = ["name", "desc", "price", "book_image"]

django-example/mysite/myapp/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from .models import Book
from .forms import BookForm
# Create your views here.


def index(request):
    # give us access to all of object inside the table
    book_list = Book.objects.all()
    context = {
        "book_list": book_list,
    }
    return render(request, "myapp/index.html", context)


def detail(request, book_id):
    book = Book.objects.get(id=book_id)
    return render(request, "myapp/detail.html", {"book": book})


def add_book(request):

    # a post request comes from add_booh page by pressing submit button
    # when a post request comes we check it
    if request.method == "POST":
        # we save the name typed bye user in the name feild
        # we should becareful about what ever we use in "" inside get function
        # it should be same as in the add_book we gave as name
        name = request.POST.get("name",)
        desc = request.POST.get("desc",)
        price = request.POST.get("price",)
        book_image = request.FILES["book_image"]

        # now we have saved them and we should save them in database
        # we create a object of our class which we have in models
        book = Book(name=name, desc=desc, price=price, book_image=book_image)
        book.save()

    # we make this view render a template with return render()
    # request and temmplate path to this view
    return render(request, "myapp/add_book.html")
    # after this we need url pattern
    # now we go to myapp/urls.py


def edit(request, id):
    book = Book.objects.get(id=id)
    # request.POST means it will be method of POST
    # request.FILES is for haveing image
    # instance is nothing but book which we want to edit and the book is coming from top we have book=Book.object
    form = BookForm(request.POST or None, request.FILES, instance=book)
    if form.is_valid():
        form.save()
        # returning homepage
        return redirect("/")
    # we passs book and form as context to edit.html
    return render(request, "myapp/edit.html", {"form": form, "book": book})


def delete(request, id):
    if request.method == "POST":
        book = Book.objects.get(id=id)
        book.delete()
        return redirect("/")
    return render(request, "myapp/delete.html")

django-example/mysite/myapp/templates/myapp/add_book.html
<!--THIS PAGE IS ONE WAY OF CREATEING FORM USING HTML-->
<!--we want to create a form here so we use the form tag-->
<!--here we use method atribute and we use post because we will post data to database-->
<!--ency is to make submit button work-->
<form method="POST" enctype="multipart/form-data">
    <!--inside any form we create in django what we need to do is adding token called csrf_token-->
    {% csrf_token %}
    <!--this is a input feild accepting text from user and it has name also it should be same as in arguments in models.py-->
    <input type="text" name="name" id="name" placeholder="enter the name of book">
    <input type="text" name="desc" id="desc" placeholder="enter book description">
    <input type="text" name="price" id="price" placeholder="enter the price of book">
    <input type="file" name="book_image" id="book_image">
    <input type="submit" name="" id=""> 
</form>

django-example/mysite/myapp/templates/myapp/base.html
<!--it goes and load any static file if it is in this folder--> 
{% load static %}

<!DOCTYPE html>
<html lang="en">

    <head>

        <!--this is bootstrap for who,e use phone to connect our app-->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

        <!--we link our style.css file with this index.html file -->
        <link rel="stylesheet" href="{% static "myapp/style.css" %}">

        <title>Document</title>

    </head>

    <body>

        <!-- Image and text -->
        <nav class="navbar navbar-dark bg-dark">
            <a class="navbar-brand" href="#">
                Book Store
            </a>
        </nav>

        <!--here the body is the name of block so we use this name in the index.html file too-->
        {% block body %}

        {% endblock %}

    </body>
</html>

django-example/mysite/myapp/templates/myapp/delete.html
<form method="POST">
    <!--in forms we always include csrf_token-->
    {% csrf_token %}
    are you sure you want to delete this book
    <input type="submit">

</form>

django-example/mysite/myapp/templates/myapp/detail.html
<!--here we use base.html all head and body tag-->
{% extends "myapp/base.html" %}

<!--this block with the name of body is the same block in base.html-->
<!--we can use it because we extend detail.html from base.html-->
{% block body %}

    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <img width="300" height="300" src="{{book.book_image.url}}"> 
            </div>
            <div class="col-md-6">
                <h2> {{book.name}} </h2>

                <h4> {{book.desc}} </h4>

                <h6> {{book.price}} </h6>

                <!--we are adding link here and the link is for edit veiw so edit veiw has a path in the urls.py-->
                <!--now here we have a button or linke in detail page wiyh name of edit by clicking on it we go to edit.html of that book-->
                <a class="btn btn-warning" href="{% url "myapp:edit" book.id  %}">edit</a>
                <a class="btn btn-danger" href="{% url "myapp:delete" book.id %}">delete</a>

            </div>
        </div>
    </div>

{% endblock %}

django-example/mysite/myapp/templates/myapp/edit.html
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <!--we have passed a conext ti this page from veiws.py-->
    <!--inside context we have form we have passed it-->
    <!--we get all feilds from form=BookForm is class and it has feilds-->
    {{form.as_p}}
    <input type="submit" name="" id="">
</form>

django-example/mysite/myapp/templates/myapp/index.html
<!--it means we use base.html(the use of bootstrap and navbar(placed in body and head tag of base.html)) in this file -->
{% extends "myapp/base.html" %}

{% block body %}

    <!--here we make the design as card card in 4 column-->
    <div class="container">
        <div class="row">
            {% for book in book_list %}
            <!--with col-md-3 we say that we have 4 column 12/3 = 4-->
            <div class="col-md-3">
                <!--when we use class as card bootstrap convert it as card-->
                    <div class="card">
                        <!--with using card-img-top class we put the image in the top of card-->
                        <img src="{{book.book_image.url}}" class="card-img-top">
                        <div class="card-body">
                            <h5 class="card-title">{{book.name}}</h5>
                            <p class="card-text">{{book.price}}</p>
                            <a class="btn btn-primary" href="{% url "myapp:detail" book.id %}">view Details</a>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>

    <!--book_list comes from views.py we pass it in context-->
    <!--we use django template language so we put our book_list inside double brockets-->
    <!--writing for loop with template language-->
    <!--for showing our book_list not in same line-->
    <!--herf= url detail book.id HERE we have a path in url.py which name is detail we pass that name-->
    <!--we say our url name is detail and with book.id we pass it-->
{% endblock %}